/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as WhoWeHelpRouteImport } from './routes/who-we-help'
import { Route as CaseStudiesFurnitureFusionRouteImport } from './routes/case-studies.furniture-fusion'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as ApiPublicFxRatesRouteImport } from './routes/api/public/fx-rates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeHelpRoute = WhoWeHelpRouteImport.update({
  id: '/who-we-help',
  path: '/who-we-help',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesFurnitureFusionRoute =
  CaseStudiesFurnitureFusionRouteImport.update({
    id: '/case-studies/furniture-fusion',
    path: '/case-studies/furniture-fusion',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFxRatesRoute = ApiPublicFxRatesRouteImport.update({
  id: '/api/public/fx-rates',
  path: '/api/public/fx-rates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/providers': typeof ProvidersRoute
  '/services': typeof ServicesRoute
  '/tools': typeof ToolsRoute
  '/who-we-help': typeof WhoWeHelpRoute
  '/case-studies/furniture-fusion': typeof CaseStudiesFurnitureFusionRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights/': typeof InsightsIndexRoute
  '/api/public/fx-rates': typeof ApiPublicFxRatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/providers': typeof ProvidersRoute
  '/services': typeof ServicesRoute
  '/tools': typeof ToolsRoute
  '/who-we-help': typeof WhoWeHelpRoute
  '/case-studies/furniture-fusion': typeof CaseStudiesFurnitureFusionRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights': typeof InsightsIndexRoute
  '/api/public/fx-rates': typeof ApiPublicFxRatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/providers': typeof ProvidersRoute
  '/services': typeof ServicesRoute
  '/tools': typeof ToolsRoute
  '/who-we-help': typeof WhoWeHelpRoute
  '/case-studies/furniture-fusion': typeof CaseStudiesFurnitureFusionRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights/': typeof InsightsIndexRoute
  '/api/public/fx-rates': typeof ApiPublicFxRatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/providers'
    | '/services'
    | '/tools'
    | '/who-we-help'
    | '/case-studies/furniture-fusion'
    | '/insights/$slug'
    | '/insights/'
    | '/api/public/fx-rates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/providers'
    | '/services'
    | '/tools'
    | '/who-we-help'
    | '/case-studies/furniture-fusion'
    | '/insights/$slug'
    | '/insights'
    | '/api/public/fx-rates'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/providers'
    | '/services'
    | '/tools'
    | '/who-we-help'
    | '/case-studies/furniture-fusion'
    | '/insights/$slug'
    | '/insights/'
    | '/api/public/fx-rates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProvidersRoute: typeof ProvidersRoute
  ServicesRoute: typeof ServicesRoute
  ToolsRoute: typeof ToolsRoute
  WhoWeHelpRoute: typeof WhoWeHelpRoute
  CaseStudiesFurnitureFusionRoute: typeof CaseStudiesFurnitureFusionRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  ApiPublicFxRatesRoute: typeof ApiPublicFxRatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-help': {
      id: '/who-we-help'
      path: '/who-we-help'
      fullPath: '/who-we-help'
      preLoaderRoute: typeof WhoWeHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/furniture-fusion': {
      id: '/case-studies/furniture-fusion'
      path: '/case-studies/furniture-fusion'
      fullPath: '/case-studies/furniture-fusion'
      preLoaderRoute: typeof CaseStudiesFurnitureFusionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fx-rates': {
      id: '/api/public/fx-rates'
      path: '/api/public/fx-rates'
      fullPath: '/api/public/fx-rates'
      preLoaderRoute: typeof ApiPublicFxRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProvidersRoute: ProvidersRoute,
  ServicesRoute: ServicesRoute,
  ToolsRoute: ToolsRoute,
  WhoWeHelpRoute: WhoWeHelpRoute,
  CaseStudiesFurnitureFusionRoute: CaseStudiesFurnitureFusionRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  ApiPublicFxRatesRoute: ApiPublicFxRatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
