import { createFileRoute } from "@tanstack/react-router";
import { ArrowUpRight, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Eyebrow, InfrastructureBackdrop, Process, Stats } from "@/components/Marketing";
import { bookingUrl, founderContent, valuePillars } from "@/lib/site-data";
import hero from "@/assets/hero-about.webp.asset.json";
import ben from "@/assets/ben-kohler-founder.png.asset.json";
const network=["Tier 1 FinTech platforms","Electronic Money Institutions (EMIs)","Liquidity providers and FX brokers","Global payment gateways and acquirers"];const outcomes=["Fast, secure settlements","Regulatory confidence","Freedom to scale","Tailored infrastructure based on your needs"];
export const Route=createFileRoute("/about")({head:()=>({meta:[{title:"About BLK.FX — Foreign Exchange, Personally"},{name:"description",content:"Founded in 2021 by Ben Kohler, BLK.FX combines private-banking service with modern fintech infrastructure."},{property:"og:title",content:"About BLK.FX"},{property:"og:description",content:"Built to fix poor service from banks and soulless technology from fintechs."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Page});
function Page(){return <main><section className="page-hero image-hero" style={{"--hero-image":`url(${hero.url})`} as React.CSSProperties}><div className="section-shell"><Eyebrow dark>Founded 2021</Eyebrow><h1>Smarter, more personal international finance.</h1><p>Founded in 2021 to challenge the poor service and hidden fees of traditional banking, BLK.FX brings high-end financial support back into international money management.</p></div></section><section className="section-space" id="story"><div className="section-shell story-grid"><div><Eyebrow>Our story</Eyebrow><h2>Built to fix what we saw broken.</h2></div><div><p>BLK.FX was built to fix what we saw broken in the industry – poor service from banks, and soulless tech from fintechs. We wanted to give clients something better: global capability, personal support, and pricing that made sense.</p></div></div></section><section className="founder-section section-space secondary-section"><div className="section-shell founder-profile"><img src={ben.url} alt="Ben Kohler, Founder and CEO"/><div><Eyebrow>About the founder</Eyebrow><h2>{founderContent.heading}</h2><strong>Ben Kohler, Founder &amp; CEO</strong><h3>{founderContent.strapline}</h3><p><b>Why I started BLK.FX.</b> {founderContent.why}</p><p><b>The Mission.</b> {founderContent.mission}</p><div className="founder-expectations">{founderContent.expectations.map(item=><span key={item}><Check/>{item}</span>)}</div><div className="support-note">Behind Ben is a dedicated customer service team available 24/7, including weekends — by phone, email and WhatsApp.</div></div></div></section><Stats/><section className="section-space" id="approach"><div className="section-shell"><Eyebrow>How we work</Eyebrow><div className="value-grid value-grid-light">{valuePillars.map(x=><article key={x.kicker}><Eyebrow>{x.kicker}</Eyebrow><h3>{x.title}</h3><p>{x.text}</p></article>)}</div><Process/></div></section><section className="section-space dark-section infrastructure-about"><InfrastructureBackdrop/><div className="section-shell"><Eyebrow dark>Built on the best infrastructure</Eyebrow><div className="infrastructure-intro"><h2>We aren&apos;t a one-size-fits-all provider.</h2><p>We don&apos;t rely on a single platform. We&apos;re your currency and payments concierge.</p></div><div className="infrastructure-grid"><div><h3>Our network</h3>{network.map(x=><p key={x}><Check/>{x}</p>)}</div><div><h3>Which means</h3>{outcomes.map(x=><p key={x}><Check/>{x}</p>)}</div></div></div></section><section className="about-closing section-space"><div className="section-shell"><h2>Whether you&apos;re sending £10k or £10 million, we&apos;ll help you do it smarter.</h2><Button asChild variant="accent" size="xl"><a href={bookingUrl} target="_blank" rel="noreferrer">Book a call with our team <ArrowUpRight/></a></Button></div></section></main>}