import { createFileRoute } from "@tanstack/react-router";
import { ArrowUpRight, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ClientLogo, Eyebrow } from "@/components/Marketing";
import { bookingUrl, clients, furnitureFusion } from "@/lib/site-data";

export const Route=createFileRoute("/case-studies/furniture-fusion")({head:()=>({meta:[{title:"Furniture Fusion Case Study — BLK.FX"},{name:"description",content:"How Furniture Fusion reduced FX costs, removed payment fees and simplified international reconciliation with BLK.FX."},{property:"og:title",content:"Furniture Fusion Case Study — BLK.FX"},{property:"og:description",content:"Around £25,000 saved each year, with fee-free payments and less reconciliation."},{property:"og:type",content:"article"},{name:"twitter:card",content:"summary_large_image"}]}),component:Page});

function Page(){const logo=clients.find(client=>client[0]==="Furniture Fusion");return <main><section className="page-hero"><div className="section-shell">{logo&&<ClientLogo client={logo}/>}<Eyebrow dark>Case study</Eyebrow><h1>Furniture Fusion</h1><p>{furnitureFusion.intro}</p></div></section><section className="section-space"><div className="section-shell case-study-page"><CaseList title="The challenge" items={furnitureFusion.challenge}/><CaseList title="What we did" items={furnitureFusion.work}/><div className="case-study-results"><Eyebrow>Results</Eyebrow><article><strong>£25,000</strong><p>saved per year, approximately</p></article><article><strong>Up to 1 hour</strong><p>less admin and reconciliation each day</p></article><article><strong>More certainty</strong><p>more predictable forecasting using forwards</p></article><article><strong>Smoother payments</strong><p>including same-day where possible</p></article></div></div></section><section className="legal-band"><div className="section-shell"><h2>Want a quick view of what you could save and simplify?</h2><p>Speak to the BLK.FX team.</p><Button asChild variant="accent" size="xl"><a href={bookingUrl} target="_blank" rel="noreferrer">Book a call with our team <ArrowUpRight/></a></Button></div></section></main>}
function CaseList({title,items}:{title:string;items:readonly string[]}){return <section><Eyebrow>{title}</Eyebrow><div>{items.map(item=><p key={item}><Check/>{item}</p>)}</div></section>}