import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, ArrowUpRight, Check, GitBranch, Minus, Star } from "lucide-react";
import { Button } from "@/components/ui/button";
import { HeroCurrencyRain, HeroGlobe } from "@/components/HeroGlobe";
import { Audience, ArrowLink, BenefitTicker, Differences, Eyebrow, FAQ, FeaturedTestimonial, FurnitureCaseStudy, FxTicker, HedgingTeaser, IntroLoader, Journey, LogoMarquee, Newsletter, Pricing, Process, Proposition, SectionIntro, ServicesScroll, Stats, StayStrip, Values } from "@/components/Marketing";
import { ProviderLogo } from "@/components/ProviderLogo";
import { bookingUrl, hiddenFxCosts, posts, providers, reviews } from "@/lib/site-data";
import benPhoto from "@/assets/team-ben.jpg.asset.json";
import ogImage from "@/assets/og-image-2026.png.asset.json";

export const Route=createFileRoute("/")({head:()=>({meta:[{title:"BLK.FX — Foreign exchange. Personally."},{name:"description",content:"Institutional-grade FX rates, international payments, multi-currency accounts and hedging with personal service."},{property:"og:title",content:"BLK.FX — Foreign exchange. Personally."},{property:"og:description",content:"Stop overpaying on FX. Better rates, smarter payments and a real person on the end of the phone."},{property:"og:type",content:"website"},{property:"og:image",content:ogImage.url},{name:"twitter:card",content:"summary_large_image"},{name:"twitter:image",content:ogImage.url}]}),component:Home});
function Home(){return <><IntroLoader/><main><section className="hero" data-hero><div className="hero-grid"/><HeroCurrencyRain/><div className="section-shell hero-layout"><div className="hero-inner"><Eyebrow dark staticText>Foreign exchange. Personally.</Eyebrow><h1><span><i>Stop</i></span><span><i>overpaying</i></span><span><i>on FX.</i></span></h1><p className="hero-copy">Foreign exchange, international payments and multi-currency accounts, backed by personal strategy and 24/7 dedicated support for every client.</p><p className="hero-subline">Most businesses don&apos;t realise how much they&apos;re losing, until they see the numbers.</p><div className="hero-actions"><Button asChild variant="accent" size="xl"><a href="#pricing">Find out how much you can save <ArrowRight/></a></Button><Button asChild variant="darkGhost" size="xl"><a href={bookingUrl} target="_blank" rel="noreferrer">Book a call with our team <ArrowUpRight/></a></Button></div></div><HeroGlobe/></div><FxTicker/></section><BenefitTicker/><LogoMarquee/><Stats/><Proposition/><Values/><Differences/><Audience/><FeaturedTestimonial/><ServicesScroll/><HedgingTeaser/><HiddenCosts/><Pricing/><StayStrip/><section className="process-journey section-space"><div className="section-shell"><Process/><Journey/></div></section><Providers/><Tools/><FurnitureCaseStudy/><Reviews/><LatestPosts/><FAQ/><Closing/></main></>}
function HiddenCosts(){return <section className="hidden-costs section-space"><div className="section-shell"><SectionIntro eyebrow="Beyond the rate" title="The rate is only part of it." copy="Most people compare FX providers on the rate. The real cost sits in the parts nobody quotes: when you convert, how the payment travels, who you call when it doesn't arrive, and what happens to the numbers you've already promised."/><div className="hidden-cost-grid" data-stagger>{hiddenFxCosts.map(([title,text],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div><div className="route-compare" data-reveal><div><strong>£100,000</strong><span>Your bank</span><i/><em>Intermediary fees</em><i/><b>£98,940 arrives</b></div><div className="direct-route"><strong>£100,000</strong><span>BLK.FX local route</span><i/><b>Full agreed amount arrives</b></div><GitBranch/></div></div></section>}
function Providers(){return <section className="section-space infrastructure-home"><div className="section-shell infrastructure-home-layout"><div><SectionIntro eyebrow="Infrastructure" title="Built on the best." copy="World-class customer service x leading financial providers."/><ArrowLink to="/providers">See our provider network</ArrowLink></div><div className="provider-row">{providers.map(p=><article className="provider-card" key={p.name} data-reveal><ProviderLogo provider={p} focusable/><p>{p.detail}</p></article>)}</div></div></section>}
function Tools(){return <section className="section-space dark-section"><div className="section-shell"><Link to="/tools" className="tools-card" data-reveal><div><Eyebrow dark>Separate product · Free tool</Eyebrow><h2>FX.Exposure</h2></div><div><p>Model multi-currency exposure, see how markets affect margins, compare hedging options and set rate alerts.</p><span className="tool-link">Explore FX.Exposure <ArrowRight/></span></div></Link></div></section>}
function Reviews(){const segment=(copy:number)=><div className="review-segment" aria-hidden={copy===1}>{reviews.map((r,i)=><article key={`${copy}-${i}`} className="service-card review-card"><span className="eyebrow">Verified on Trustpilot · {String(i+1).padStart(2,"0")}</span><div>{[1,2,3,4,5].map(x=><Star key={x} fill="currentColor" size={16}/>)}</div><p>“{r}”</p></article>)}</div>;return <section className="section-space reviews"><div className="section-shell"><SectionIntro eyebrow="Client reviews" title="Service you can put a name to." copy="Read what clients say about working with BLK.FX."/><div className="review-rating"><strong>4.7/5</strong><span>{[1,2,3,4,5].map(x=><Star key={x} fill="currentColor" size={18}/>)}</span><span className="eyebrow">Trustpilot</span></div><div className="review-viewport"><div className="review-track">{segment(0)}{segment(1)}</div></div><Button asChild variant="outline" size="xl" className="mt-6"><a href="https://uk.trustpilot.com" target="_blank" rel="noreferrer">Review us on Trustpilot <ArrowUpRight/></a></Button></div></section>}
function LatestPosts(){return <section className="latest-posts section-space"><div className="section-shell"><SectionIntro eyebrow="Latest insights" title="Useful thinking. No jargon."/><div className="post-grid" data-stagger>{posts.slice(0,3).map(p=><Link to="/insights/$slug" params={{slug:p.slug}} className="insight-card" key={p.slug}><div><img src={p.image} alt="" loading="lazy"/></div><span>{p.category} · {p.date}</span><h3>{p.title}</h3></Link>)}</div><ArrowLink to="/insights">View all insights</ArrowLink></div></section>}
const auditPoints=["Where you’re overpaying","How to protect your margins","Whether your current provider is holding you back","What a smarter FX setup would look like","Simple wins most CFOs and FDs overlook"];
function Closing(){return <section className="closing dark-section"><div className="section-shell"><Eyebrow dark>Free FX strategy audit</Eyebrow><h2>Are you losing money on your FX without realising it?</h2><div className="closing-grid"><div><ul>{auditPoints.map(point=><li key={point}><Check/>{point}</li>)}</ul><p>Let&apos;s streamline your FX, reduce unnecessary spend and give you total clarity, backed by dedicated support around the clock.</p></div><div className="ben-card"><img src={benPhoto.url} alt="Ben Kohler, Founder and CEO"/><div><Button asChild variant="accent" size="xl"><a href={bookingUrl} target="_blank" rel="noreferrer">Book a call with our team <ArrowUpRight/></a></Button><small>Thirty minutes with our team to uncover quick wins and hidden costs.</small></div></div></div><Newsletter/></div></section>}