import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, ArrowUpRight, Banknote, Building2, Check, CircleDollarSign, Clock3, LockKeyhole, Route as RouteIcon, WalletCards } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Eyebrow, Newsletter } from "@/components/Marketing";
import { bookingUrl, consultancyLine, hedgingApproaches, services } from "@/lib/site-data";

export const Route=createFileRoute("/services")({head:()=>({meta:[{title:"FX Services — BLK.FX"},{name:"description",content:"Business FX, international payments, multi-currency accounts, hedging, commercial finance and private client FX."},{property:"og:title",content:"FX Services — BLK.FX"},{property:"og:description",content:"Six services. One conversation."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:ServicesPage});

function ServicesPage(){const[active,setActive]=useState<string>(services[0].id);const chipRefs=useRef<Record<string,HTMLAnchorElement|null>>({});
 useEffect(()=>{const update=()=>{const marker=window.scrollY+400;let current:string=services[0].id;for(const service of services){const element=document.getElementById(service.id);if(element&&element.offsetTop<=marker)current=service.id}setActive(current)};window.addEventListener("scroll",update,{passive:true});const hash=window.location.hash.slice(1);if(hash)window.setTimeout(()=>scrollToService(hash,false),180);else update();return()=>window.removeEventListener("scroll",update)},[]);
 useEffect(()=>{chipRefs.current[active]?.scrollIntoView({behavior:"smooth",block:"nearest",inline:"center"})},[active]);
 const scrollToService=(id:string,smooth=true)=>{const target=document.getElementById(id);if(!target)return;const nav=document.querySelector<HTMLElement>(".site-nav");const subnav=document.querySelector<HTMLElement>(".service-subnav");const offset=(nav?.offsetHeight??64)+(subnav?.offsetHeight??50)+28;const top=target.getBoundingClientRect().top+window.scrollY-offset;setActive(id);window.history.replaceState(null,"",`/services#${id}`);window.scrollTo({top,behavior:smooth?"smooth":"auto"});target.classList.add("is-targeted");window.setTimeout(()=>target.classList.remove("is-targeted"),1400)};
 return <main><section className="page-hero services-hero"><div className="section-shell"><Eyebrow dark>Services</Eyebrow><h1>Everything FX.<br/>Nothing extra.</h1><p>Convert, send, hold, protect and fund money across borders with better infrastructure and dedicated support around the clock.</p></div></section><nav className="service-subnav" aria-label="Services on this page"><div className="section-shell">{services.map(service=><a ref={node=>{chipRefs.current[service.id]=node}} key={service.id} href={`#${service.id}`} onClick={event=>{event.preventDefault();scrollToService(service.id)}} className={active===service.id?"is-active":""} aria-current={active===service.id?"location":undefined}>{service.verb}</a>)}</div></nav><section className="services-detail"><div className="section-shell">{services.map((service,index)=><article id={service.id} className="service-detail-block" key={service.id} data-stagger><div className="service-detail-copy"><span className="number">{service.number} / {service.verb}</span><h2>{service.title}</h2><p>{service.text}</p><ServiceExtra id={service.id}/><div className="service-bullets">{service.bullets.map(bullet=><span key={bullet}><Check/>{bullet}</span>)}</div><Button asChild variant="accent" size="xl"><a href={bookingUrl} target="_blank" rel="noreferrer">Book a call with our team <ArrowUpRight/></a></Button></div><ServiceVisual index={index}/></article>)}</div></section><aside className="support-strip"><div className="section-shell"><span>24/7</span><p><strong>Every service includes dedicated support.</strong> Call, email or WhatsApp our team at any hour, including weekends.</p></div></aside><section className="section-space dark-section"><div className="section-shell"><Eyebrow dark>Built around you</Eyebrow><h2 className="service-closing-title">One point of contact.<br/>More ways to move.</h2><p className="service-consultancy">{consultancyLine}</p><Button asChild variant="accent" size="xl"><a href={bookingUrl} target="_blank" rel="noreferrer">Book a call with our team <ArrowUpRight/></a></Button></div></section><div className="newsletter-band"><div className="section-shell"><Newsletter/></div></div></main>}
function ServiceExtra({id}:{id:string}){if(id==="international-payments")return <div className="service-extra"><strong>Free international payments</strong><p>£0 / €0 / $0 payment fees. The only cost is a very competitive FX margin.</p></div>;if(id==="fx-risk-management-hedging")return <div className="service-extra"><strong>What is a forward contract?</strong><p>A forward contract lets you lock in an exchange rate today for a future payment, so you know what you will pay or receive later.</p><div className="mini-option-grid">{hedgingApproaches.map(([title,text])=><span key={title}><b>{title}</b>{text}</span>)}</div><p><b>Importing goods:</b> lock rates so costs do not jump and margins stay protected. <b>Paying tuition:</b> lock a rate at the start of the year to avoid last-minute surprises.</p><small>Structured forwards can add flexibility when payment dates are not exact, up to a defined window.</small></div>;if(id==="private-client-fx")return <div className="service-extra"><strong>Private, global and time-sensitive</strong><p>Support via WhatsApp, phone, email or app; regular payments for family, tuition, property and lifestyle; and wires sent for you once authorised.</p><small>Transfers between BLK.FX multi-currency accounts are fee-free.</small></div>;return null}
function ServiceVisual({index}:{index:number}){const icons=[CircleDollarSign,RouteIcon,WalletCards,LockKeyhole,Banknote,Building2];const Icon=icons[index]??CircleDollarSign;const labels=[["GBP","EUR","1.1684"],["London","Dubai","Same day"],["GBP","USD","CAD"],["EUR/GBP","6 months","Locked"],["Facility","Working capital","Ready"],["Exchange","Completion","On time"]][index]??[];return <div className={`service-visual visual-${index+1}`} aria-hidden="true"><header><Icon/><span>BLK.FX / 0{index+1}</span><i/></header><div className="visual-core">{index===1?<RouteIcon/>:index===3?<LockKeyhole/>:index===5?<Clock3/>:<Icon/>}</div><div className="visual-data">{labels.map((label,i)=><span key={label} style={{"--visual-index":i} as React.CSSProperties}>{label}{i<labels.length-1&&<ArrowRight/>}</span>)}</div></div>}