import { Link } from "@tanstack/react-router";
import { ArrowRight, ArrowUpRight, Check, Minus, Play, ShieldCheck } from "lucide-react";
import { useEffect, useMemo, useRef, useState, type CSSProperties, type FormEvent, type ReactNode } from "react";
import { toast } from "sonner";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Slider } from "@/components/ui/slider";
import { audienceHighlights, BANK_RANGE, benefits, capabilities, clients, consultancyLine, currencyAccounts, differences, faqs, featuredTestimonial, FEE_RANGE, furnitureFusion, hedgingApproaches, PAYMENT_FEES, processSteps, reasonsClientsStay, services, valuePillars, whyBlkFx } from "@/lib/site-data";
import videoPoster from "@/assets/video-poster.jpg.asset.json";
import globeVideo from "@/assets/black-globe.mp4.asset.json";
import { Logo } from "@/components/Logo";

export function Eyebrow({children,dark=false,staticText=false}:{children:ReactNode;dark?:boolean;staticText?:boolean}){return <p className={`eyebrow ${dark?"text-dark-muted":""}`} {...(!staticText?{"data-scramble":""}:{})}><span className="eyebrow-dot"/>{children}</p>}
export function SectionIntro({eyebrow,title,copy,dark=false}:{eyebrow:string;title:string;copy?:string;dark?:boolean}){return <div className="section-intro" data-reveal><Eyebrow dark={dark}>{eyebrow}</Eyebrow><h2>{title}</h2>{copy&&<p className={dark?"text-dark-muted":"text-muted-foreground"}>{copy}</p>}</div>}
export function ArrowLink({to,children}:{to:string;children:ReactNode}){return to.startsWith("http")?<a className="arrow-link" href={to} target="_blank" rel="noreferrer">{children}<ArrowUpRight/></a>:<Link className="arrow-link" to={to}>{children}<ArrowRight/></Link>}

export function IntroLoader(){const[show,setShow]=useState(false);useEffect(()=>{if(!sessionStorage.getItem("blk-intro")){setShow(true);sessionStorage.setItem("blk-intro","1");const t=setTimeout(()=>setShow(false),1800);return()=>clearTimeout(t)}return undefined},[]);return show?<div className="intro-loader"><Logo className="loader-logo"/></div>:null}

const mockPairs:[string,number][]=[["GBP/USD",1.3472],["GBP/EUR",1.1608],["EUR/GBP",.8614],["EUR/USD",1.1606],["USD/CAD",1.3761],["GBP/AED",4.9472],["AUD/GBP",.5148],["GBP/CHF",1.0712],["USD/JPY",148.62],["GBP/ZAR",23.814]];
type Rate={pair:string;rate:number;change:number|null}; const fmt=(pair:string,n:number)=>n.toFixed(pair.includes("JPY")?2:4);
export function FxTicker(){const[rates,setRates]=useState<Rate[]>(mockPairs.map(([pair,rate])=>({pair,rate,change:null})));const[status,setStatus]=useState<"indicative"|"live"|"delayed">("indicative");const[updated,setUpdated]=useState("");const previousRates=useRef<Record<string,number>>({});const[flashing,setFlashing]=useState<Set<string>>(new Set());
 useEffect(()=>{let timer:ReturnType<typeof setInterval>|undefined;let flashTimer:ReturnType<typeof setTimeout>|undefined;let cancelled=false;async function load(){try{const res=await fetch("/api/public/fx-rates");if(!res.ok)return;const d=await res.json() as{status:"live"|"delayed";updatedAt:string;rates:Rate[]};if(cancelled||!d.rates)return;const changed=new Set(d.rates.filter(r=>previousRates.current[r.pair]!==undefined&&previousRates.current[r.pair]!==r.rate).map(r=>r.pair));previousRates.current=Object.fromEntries(d.rates.map(r=>[r.pair,r.rate]));setRates(d.rates);setStatus(d.status);setUpdated(new Date(d.updatedAt).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",timeZone:"Europe/London"}));setFlashing(changed);clearTimeout(flashTimer);flashTimer=setTimeout(()=>setFlashing(new Set()),1400)}catch{/* keep fallback */}}const start=()=>{clearInterval(timer);timer=setInterval(load,120000)};const onVis=()=>{if(document.hidden)clearInterval(timer);else{load();start()}};load();start();document.addEventListener("visibilitychange",onVis);return()=>{cancelled=true;clearInterval(timer);clearTimeout(flashTimer);document.removeEventListener("visibilitychange",onVis)}},[]);
 const label=status==="indicative"?"Indicative":status==="delayed"?`Delayed · Updated ${updated}`:`Live mid-market rates · Updated ${updated}`;const segment=(copy:number)=><div className="ticker-segment" aria-hidden={copy===1}>{rates.map(r=>{const direction=r.change===null?"flat":r.change>0?"up":r.change<0?"down":"flat";const change=r.change===null?null:r.change===0?"0.00%":`${r.change>0?"▲ +":"▼ −"}${Math.abs(r.change).toFixed(2)}%`;return <div className={`ticker-item ${flashing.has(r.pair)?"rate-flash":""}`} key={`${r.pair}-${copy}`}><span>{r.pair}</span><strong>{fmt(r.pair,r.rate)}</strong>{change&&<em className={direction}>{change}</em>}<b aria-hidden="true">•</b></div>})}</div>;return <div className="ticker-wrap"><div className="ticker" aria-label={`${label} foreign exchange rates`}><div className="ticker-row">{segment(0)}{segment(1)}</div><span className="indicative"><strong>{label}</strong><small>Mid-market rates for information only. Not a quote.</small></span></div></div>}

export function ClientLogo({client}:{client:(typeof clients)[number]}){const[name,image,treatment,scale]=client;return <span className={`client-logo ${treatment}`}><img src={image} alt={name} loading="lazy" style={{"--logo-scale":scale} as CSSProperties} onError={e=>{e.currentTarget.hidden=true;e.currentTarget.nextElementSibling?.removeAttribute("hidden")}}/><b hidden>{name}</b></span>}
export function LogoMarquee(){const segment=(copy:number)=><div className="marquee-segment" aria-hidden={copy===1}>{clients.map(client=><ClientLogo client={client} key={`${client[0]}-${copy}`}/>)}</div>;return <section className="proof-band"><div className="section-shell"><Eyebrow>Trusted by</Eyebrow></div><div className="logo-marquee"><div className="marquee-track">{segment(0)}{segment(1)}</div></div></section>}
export function BenefitTicker(){const segment=(copy:number)=><div className="marquee-segment" aria-hidden={copy===1}>{benefits.map(item=><span key={`${item}-${copy}`}><b/> {item}</span>)}</div>;return <div className="benefit-ticker"><div className="marquee-track">{segment(0)}{segment(1)}</div></div>}
function AnimatedStat({value,suffix,decimals}:{value:number;suffix:string;decimals:number}){const ref=useRef<HTMLSpanElement>(null);const[display,setDisplay]=useState(0);useEffect(()=>{const node=ref.current;if(!node)return;let frame=0;let start=0;const observer=new IntersectionObserver(([entry])=>{if(!entry?.isIntersecting)return;observer.disconnect();const run=(time:number)=>{if(!start)start=time;const progress=Math.min(1,(time-start)/1800);setDisplay(value*(1-Math.pow(1-progress,3)));if(progress<1)frame=requestAnimationFrame(run)};frame=requestAnimationFrame(run)},{threshold:.35});observer.observe(node);return()=>{observer.disconnect();cancelAnimationFrame(frame)}},[value]);return <span ref={ref}>{display.toLocaleString("en-GB",{minimumFractionDigits:decimals,maximumFractionDigits:decimals})}{suffix}</span>}
export function Stats(){const stats=[[30,"+","Clients across countries",0],[35,"+","Currencies",0],[500,"m+","FX volume",0],[5000,"+","International payments completed",0],[4.7,"/5","Trustpilot · Excellent",1]]as const;return <section className="stats"><div className="section-shell stats-grid" data-stagger>{stats.map(([n,s,l,d])=><div key={l}><p><AnimatedStat value={n} suffix={s} decimals={d}/></p><span>{l}</span><i data-grow/></div>)}</div></section>}
export function Differences(){return <section className="section-space differences"><div className="section-shell"><SectionIntro eyebrow="What makes us different" title="Better infrastructure. Personal service."/><div className="difference-grid">{differences.map(([title,text],i)=><article key={title} data-reveal><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>}
export function Values(){return <section className="values dark-section section-space"><div className="section-shell"><SectionIntro dark eyebrow="Why BLK.FX" title="What you are actually buying." copy="Anyone can quote a rate. Rates are public. The difference is what surrounds the trade."/><div className="value-grid">{valuePillars.map(x=><article key={x.kicker} data-reveal><Eyebrow dark>{x.kicker}</Eyebrow><h3>{x.title}</h3><p>{x.text}</p></article>)}</div><Accordion type="single" collapsible className="why-accordion">{whyBlkFx.map(([title,text],i)=><AccordionItem value={`why-${i}`} key={title}><AccordionTrigger><span>{String(i+1).padStart(2,"0")}</span>{title}</AccordionTrigger><AccordionContent>{text}</AccordionContent></AccordionItem>)}</Accordion></div></section>}
export function StayStrip(){return <section className="stay-strip"><div className="section-shell"><Eyebrow>Why clients stay</Eyebrow><div>{reasonsClientsStay.map((reason,i)=><p key={reason}><span>0{i+1}</span>{reason}</p>)}</div></div></section>}

export function Proposition(){const[playing,setPlaying]=useState(false);return <section className="proposition section-space"><div className="section-shell"><SectionIntro eyebrow="The BLK proposition" title="Move money globally — with transparency and control." copy="For businesses, partners and globally mobile clients."/><div className="currency-strip" aria-label="Available currency accounts">{currencyAccounts.map(currency=><span key={currency}>{currency}</span>)}</div><div className="proposition-grid"><div className="video-frame" data-reveal>{playing?<iframe src="https://player.vimeo.com/video/1027741242?h=378ed58ffa&title=0&byline=0&portrait=0&autoplay=1" title="Experience BLK.FX" allow="autoplay; fullscreen; picture-in-picture" allowFullScreen/>:<><img src={videoPoster.url} alt="BLK.FX brand film" loading="lazy"/><Button variant="accent" size="icon" onClick={()=>setPlaying(true)} aria-label="Play the BLK.FX introduction video"><Play fill="currentColor"/></Button></>}</div><div className="capability-grid">{capabilities.map(([title,text],i)=><article key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}<Button asChild variant="ink"><a href="https://meetings.hubspot.com/ben-kohler/intro-call-ben" target="_blank" rel="noreferrer">Talk to a specialist <ArrowRight/></a></Button></div></div></div></section>}
export function ServicesScroll(){return <section className="services-pin" id="services" data-service-pin><div className="section-shell"><SectionIntro eyebrow="Services" title="Six services. One conversation." copy={consultancyLine}/></div><div className="services-track" data-service-track>{services.map(s=><Link to="/services" hash={s.id} className="service-card" key={s.verb}><div><span>{s.number}</span><Minus/></div><p>{s.verb}</p><h3>{s.title}</h3><p>{s.text}</p><ul>{s.bullets.map(b=><li key={b}>{b}</li>)}</ul><span className="service-read">Read more <ArrowRight/></span></Link>)}<div className="service-end"><p>Better rates.<br/>Sharper thinking.<br/>Human service.</p><Button asChild variant="accent" size="xl"><Link to="/services">Explore services <ArrowRight/></Link></Button></div></div></section>}
export function SavingsCalculator(){const[volume,setVolume]=useState(40000);const[bank,setBank]=useState(3);const saving=useMemo(()=>Math.round(volume*12*((bank-.4)/100)),[volume,bank]);return <div className="calculator" data-reveal><div className="calculator-head"><div><Eyebrow>Your potential saving</Eyebrow><p className="saving" key={saving}>£{saving.toLocaleString()}<small>/year</small></p></div><span>BLK.FX midpoint fixed at 0.4%</span></div><label>Monthly FX volume <strong>£{volume.toLocaleString()}</strong></label><Slider value={[volume]} min={10000} max={5000000} step={10000} onValueChange={v=>setVolume(v[0]??40000)}/><label>Current bank margin <strong>{bank.toFixed(1)}%</strong></label><Slider value={[bank]} min={1} max={3.5} step={.1} onValueChange={v=>setBank(v[0]??3)}/><p className="calculator-note">Illustrative only. Actual savings depend on your existing rate and transaction profile.</p></div>}
export function Pricing(){const free=["International payments — £0 / €0 / $0","Multi-currency accounts in your name","Strategy and treasury consultancy","Risk management and hedging structure","Market analysis on the pairs you are exposed to","24/7 support when a payment needs attention"];return <section className="pricing section-space" id="pricing"><div className="section-shell"><SectionIntro eyebrow="Straightforward pricing" title="The rate you see is not the rate you get." copy="The exchange rate matters, but it is only one part of the decision. Service, strategy, timing and what happens when a payment needs attention matter too."/><div className="bar-compare"><div className="bar-scale"><span>0%</span><span>1.75%</span><span>3.5%</span></div><div><span>High street bank · Taken quietly inside the rate you are quoted.</span><strong>{BANK_RANGE}</strong></div><i className="bar-bank" data-grow/><div><span>BLK.FX · Very competitive rates, with no hidden fees.</span><strong className="text-orange">{FEE_RANGE}</strong></div><i className="bar-blk" data-grow/><small>Indicative margin comparison. Your quote depends on the currency, amount and timing.</small></div><FeeComparison/><div className="pricing-grid" data-stagger><div className="plain-panel"><Eyebrow>No charge — £0</Eyebrow>{free.map(x=><p key={x}><Check/>{x}</p>)}</div><div className="ink-panel"><Eyebrow dark>Where we earn</Eyebrow><p>The margin on your currency conversion, and nothing else — kept very competitive, typically {FEE_RANGE}.</p><small>No account opening, maintenance or onboarding fees.</small></div></div><SavingsCalculator/></div></section>}
export function FeeComparison(){return <div className="fee-compare" data-stagger><article><Eyebrow>High street bank</Eyebrow><strong data-fee-counter>{PAYMENT_FEES.bank}</strong><p>Typical international payment fee, plus the margin in the rate.</p><small>Typical bank charges; varies by bank.</small></article><article><Eyebrow>BLK.FX</Eyebrow><strong>£0 · Free</strong><p>{PAYMENT_FEES.blk} payment fees. Completely free.</p><small>Same day, up to next day.</small></article></div>}
const audienceRows=["CFOs","Founders","SPVs","Trusts","Funds","Private Equity","Ecommerce","Private Clients","Property","Finance Directors","Owner-Managers","Venture Capital","Professional Services","Scaling Businesses","International Property","Artists & Agents","Athletes"];
export function Audience(){const row=(reverse=false)=><div className={`marquee-track ${reverse?"reverse":""}`}>{[0,1].map(copy=><div className="marquee-segment" aria-hidden={copy===1} key={copy}>{(reverse?[...audienceRows].reverse():audienceRows).map(x=><span key={`${x}-${copy}`}>{x}<b>•</b></span>)}</div>)}</div>;return <section className="audience section-space dark-section" id="who-we-help"><div className="section-shell"><SectionIntro dark eyebrow="Who this is for" title="Find yourself on this list."/><Accordion className="audience-accordion" type="single" collapsible>{audienceHighlights.map((x,i)=><AccordionItem value={x.id} key={x.id}><AccordionTrigger><span>0{i+1}</span>{x.title}</AccordionTrigger><AccordionContent>{x.text}<Link className="audience-more" to="/who-we-help" hash={x.id}>Learn more <ArrowRight/></Link></AccordionContent></AccordionItem>)}</Accordion></div><div className="audience-marquee">{row()}{row(true)}</div></section>}
export function Process(){return <section className="process" id="approach"><SectionIntro eyebrow="How it works" title="Three steps, and you are trading."/><div className="process-grid">{processSteps.map(x=><article key={x[0]} data-reveal><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><a className="regulated-badge" href="#regulatory"><ShieldCheck/> <span><strong>Regulated</strong> BLK.FX works only with regulated execution partners across the UK, the EEA and the US.</span></a><p className="process-note">We only make money on the spread/margin we take when our clients convert currencies.</p></section>}
export function Journey(){const rail="GBP · EUR · USD · CHF · AED · CAD · AUD · Faster Payments · SEPA · SWIFT · ACH · ";return <section className="journey"><Eyebrow>International payments</Eyebrow><h2>Two routes. One clear winner.</h2><p className="journey-lede">Receive and send payments internationally with less friction, backed by our dedicated customer service team 24/7.</p><div className="speed-race" data-stagger><div><strong>BLK.FX · £0 / €0 / $0</strong><span>Completely free · Same day, up to next day.</span><i className="speed-dot speed-fast"/></div><div><strong>High street bank · around £15 / €20 / $20</strong><span>Plus FX margin · Same day, up to 5 working days.</span><i className="speed-dot speed-slow"/></div></div><small className="bank-note">Typical bank charges; varies by bank.</small><div className="channel-chips"><span>Phone</span><span>Email</span><span>WhatsApp</span><span>24/7</span></div><p className="journey-help">If a payment does not arrive when expected, our 24/7 team investigates what happened and helps move it forward.</p><div className="rail-ticker"><div className="marquee-track"><span>{rail}</span><span aria-hidden="true">{rail}</span></div></div></section>}

export function HedgingTeaser(){return <section className="hedging-teaser dark-section section-space"><div className="section-shell"><SectionIntro dark eyebrow="Hedging, in plain English" title="Fix the price now. Reduce surprises later." copy="Exchange rates move all the time. If you need to pay or receive money in another currency later, a worse rate could affect your budget. Hedging is simply a plan to reduce those surprises."/><div className="hedging-grid" data-stagger>{hedgingApproaches.map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div><ArrowLink to="/services#fx-risk-management-hedging">Understand your options</ArrowLink></div></section>}
export function FeaturedTestimonial(){return <section className="featured-testimonial"><div className="section-shell"><blockquote>“{featuredTestimonial.quote}”</blockquote><p><strong>{featuredTestimonial.author}</strong><span>{featuredTestimonial.company}</span></p></div></section>}
export function FurnitureCaseStudy(){const logo=clients.find(client=>client[0]==="Furniture Fusion");return <section className="case-teaser section-space"><div className="section-shell"><div>{logo&&<ClientLogo client={logo}/>}<Eyebrow>Case study</Eyebrow><h2>Furniture Fusion</h2><p>{furnitureFusion.intro}</p><Button asChild variant="ink"><Link to="/case-studies/furniture-fusion">Read the case study <ArrowRight/></Link></Button></div><div className="case-results" data-stagger><article><strong><AnimatedStat value={25000} suffix="" decimals={0}/></strong><span>£ saved per year, approximately</span></article><article><strong><AnimatedStat value={1} suffix="" decimals={0}/></strong><span>hour saved each day, up to</span></article><article><strong>£0</strong><span>payment fees</span></article></div></div></section>}
export function InfrastructureBackdrop(){return <video className="globe-video" autoPlay muted loop playsInline aria-hidden="true"><source src={globeVideo.url} type="video/mp4"/></video>}
export function Newsletter(){function submit(e:FormEvent){e.preventDefault();toast.success("You’re on the list.",{description:"Your first Friday update will arrive soon."})}return <section className="newsletter" id="market-update"><div className="newsletter-grid"><div><Eyebrow>Weekly FX Market Update</Eyebrow><h2>Your shortcut to staying market-ready.</h2><p>Smart, concise weekly insights for CFOs, FDs, Treasury Managers and CEOs who need clarity, not chaos. Every Friday, in under five minutes. No jargon. No doom-scrolling.</p><blockquote>“His weekly updates via email keep me informed and up-to-date.”</blockquote></div><form onSubmit={submit}><label htmlFor="news-email">Work email</label><div><Input id="news-email" required type="email" placeholder="you@company.com"/><Button variant="ink" size="xl">Sign up <ArrowRight/></Button></div><p>Unsubscribe any time.</p></form></div></section>}
export function FAQ(){return <section className="section-space faq"><div className="section-shell faq-grid"><SectionIntro eyebrow="Common questions" title="Useful answers. Straight up."/><Accordion type="single" collapsible>{faqs.map(([q,a],i)=><AccordionItem value={`q${i}`} key={q}><AccordionTrigger><span>0{i+1}</span>{q}</AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>}